### PR TITLE
Fix for Tumblr not Finding a post via postid without the name of the blog

### PR DESCRIPTION
**Pull request by ghayes7**
Fix for Tumblr not Finding a post via post-id without the name of the blog it's posted on.

Added an optional param to GetPostAsync allowing the user to specify a blog name. Might want to consider making it a required param as I've not yet found a post which can be found without the blog Name...

### CODE REVIEW

**Comment by piedoom** [comment]
Good catch, thanks!  I believe you're correct on it being required, so if you could update your addition to require the param without a default I'll go ahead and merge.

**Comment by ghayes7** [comment]
Sure thing, done.

**Comment by ghayes7** [comment]
> Good catch, thanks! I believe you're correct on it being required, so if you could update your addition to require the param without a default I'll go ahead and merge.

Sure thing, done.

**Comment by piedoom** [comment]
Thanks!

**Pull request merged**
