### PR TITLE
Removing enum for avatar shape

### PR DESCRIPTION
**Pull request by rosalindwills**
Quick update to my previous PR. Turns out that AvatarShape can also be an empty string (??), so I switched it to a string instead of an enum in the Note object.

### CODE REVIEW

**Comment by piedoom** [comment]
I see you're getting accustomed to some of the weird API decisions Tumblr has implemented, haha.

It's my guess that the empty string is from users that had their icons before the setting was introduced. 

It's been a while since I've used Newtonsoft, but I think a more elegant solution might be to just cast the `""` string to the default (square) Enum value, as I think the readability and enumerations is far greater than an arbitrary string.  I believe this can be as simple as tagging your enum with stuff from newtonsoft.

https://stackoverflow.com/a/18551699/2584408

Let me know what you think of this.

**Comment by rosalindwills** [comment]
@piedoom Ahh -- perfect! I didn't like the string solution much but couldn't figure out how to have it elegantly parse the empty string to enum; this is much better. Updated!

**Comment by piedoom** [comment]
Great, merged :)

edit: oops

**Comment by piedoom** [comment]
There we go.  CI will push to NuGet in a few.

**Comment by ceyko** [comment]
@rosalindwills @piedoom In light of this pull, we've fixed this bug on the backend :)

You should no longer be seeing any `"avatar_shape": ""` in API responses for Note objects.

That said, it doesn't hurt to stay defensive in strongly typed languages. But just wanted to let you know regardless.

If you see any future backend issues like this, you can also report them on one of our [API Client repos](https://github.com/tumblr?q=api) or on the [tumblr-api mailing list](https://groups.google.com/forum/#!forum/tumblr-api).

**Comment by piedoom** [comment]
That's awesome to hear!  Thanks for the update.

**Pull request merged**
